### PR TITLE
Auto update

### PR DESCRIPTION
**Pull request by tasleson**
Add auto client update capability

The node_manager can with this change push newer client code down
to the clients.
    
 Theory of operation:
   1. node connects to node manager
   2. node manager requests the md5 for 1 or more files of interest
   3. If any of the files don't match expectations, push the correct files down to the client
   4. Re-validate the md5 of the files
   5. node manager initiates a restart of the node
    
 To push out new code, copy code to nodemanager system and restart it the
 service.

Note:
* We will only allow updates and file checks for files in the same directory as `node.py`.

### CODE REVIEW

**Comment by tasleson** [comment]
@joehandzik @cathay4t Please take a look at this change and see what you think.  I thought about doing all sorts of additional functionality to ensure the client could fail safe etc., but in the end it's OK if the client gets borked once in a while :-)

**Comment by joehandzik** [comment]
@tasleson Sorry for taking so long to look at this. It looks pretty neat, no real concerns on my end about giving this a shot.

**Comment by tasleson** [comment]
@joehandzik Please update your client and I'll update the node manager tomorrow.

**Comment by cathay4t** [comment]
@tasleson I haven't read the code yet. The test still works well. https://github.com/libstorage/libstoragemgmt/pull/269 The megaraid is using the auto_update branch.

**Comment by joehandzik** [comment]
@tasleson Both reconnected and updated to this branch.

**Comment by tasleson** [comment]
@joehandzik @cathay4t  Thanks!

**Pull request merged**
